### ISSUE TITLE
Feature Request: Tab completion

### ISSUE THREAD

**Issue by ejether** [reactiveops/reckoner#6]
Carried over from: https://github.com/reactiveops/autohelm/issues/38

**Comment by endzyme** [comment]
http://click.palletsprojects.com/en/7.x/bashcomplete/ - to capture a thought

**Comment by endzyme** [comment]
Looks like this is already supported https://click.palletsprojects.com/en/7.x/bashcomplete/#activation-script

BASH: (Add to your `.bashrc`)
```shell
eval "$(_RECKONER_COMPLETE=source reckoner)"
```

ZSH: (add to `.zshrc`)
```shell
eval "$(_RECKONER_COMPLETE=source_zsh reckoner)"
```

**Comment by sudermanjr** [comment]
I think you missed the original issue description:

`When updating a single chart, it would be really cool if autohelm plot course.yml --heading <tab> auto-completed the chart names.`

This is for auto-completion of `--only` or `--heading`

Just an idea I had back in the day.  Not super easy to implement and possibly not valuable enough to warrant doing.

**Comment by endzyme** [comment]
Ah - sorry - yeah i didn't see that context in the transfer. Jumping the gun I guess. It would be hard without having the reckoner course file already accessible, but when you're writing out the command you generally haven't written the course file out yet. Kind of tricky. 

@sudermanjr do you mind if i close this since I am on the same page that the value probably won't match the effort needed to implement?

**Comment by ejether** [comment]
https://stackoverflow.com/questions/52282173/extending-bash-completion-with-python-click
Click is awesome and it doesn't look like it would be too much effort.

**Comment by sudermanjr** [comment]
I'm not particularly attached to the feature, and I haven't heard anyone clamoring for it.  I'm good with whatever.

**Comment by endzyme** [comment]
Sounds good - we'll readdress if it comes up again.
